table Customer
	lineageTag: c0010001-0001-0001-0001-000000000001

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: c0020001-0001-0001-0001-000000000001
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = User

	column CustomerName
		dataType: string
		lineageTag: c0030001-0001-0001-0001-000000000001
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = User

	column City
		dataType: string
		lineageTag: c0040001-0001-0001-0001-000000000001
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = User

	partition Customer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Customer.csv"), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"CustomerKey", Int64.Type}, {"CustomerName", type text}, {"City", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

